# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpas < Formula
  desc "Mpas CLI"
  homepage ""
  version "0.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.5.4/mpas_0.5.4_darwin_amd64.tar.gz"
      sha256 "55696416948e8b2e4fd7b40a2814cf0209718afe0027e8f29ebe98a063dc2ab0"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.5.4/mpas_0.5.4_darwin_arm64.tar.gz"
      sha256 "77aeaadee89dbf71f303211e1d98956cbe7300726b825dde1a0dceeb090f6cdc"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.5.4/mpas_0.5.4_linux_arm64.tar.gz"
      sha256 "16ead9f3982d32fa347a5d37880e47f787960d584066905f184d382ee33ba9bf"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.5.4/mpas_0.5.4_linux_amd64.tar.gz"
      sha256 "3a6cbd8fa0a159aeeed8aabae1aed7b62c0e858aac344c6d3ee0b70c36938a89"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
  end

  test do
    system "#{bin}/mpas --version"
  end
end
