# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpas < Formula
  desc "Mpas CLI"
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.2.0/mpas_0.2.0_darwin_arm64.tar.gz"
      sha256 "7c5e8da176f46e5a3411f16fbacc817f17e9a672be43d300c71520bcd62ed5f1"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.2.0/mpas_0.2.0_darwin_amd64.tar.gz"
      sha256 "3ae31ad00a5cbfe0493b929387778901e3257b84aae2da1938d407f7405d3b7f"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.2.0/mpas_0.2.0_linux_arm64.tar.gz"
      sha256 "d746478ed0788968aae1d0cbcc90399af9558fd851c80d2f506a9d3d6d694f30"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/open-component-model/MPAS/releases/download/v0.2.0/mpas_0.2.0_linux_amd64.tar.gz"
      sha256 "1642406b1fabda17d4db3ad14dab958d3f8047c2e4e00870d3b009b3f5505260"

      def install
        bin.install "mpas"

        generate_completions_from_executable(bin/"mpas", "completion")
      end
    end
  end

  test do
    system "#{bin}/mpas --version"
  end
end
