# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocm < Formula
  desc "The OCM CLI makes it easy to create component versions and embed them in build processes."
  homepage "https://ocm.software/"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/open-component-model/ocm/releases/download/v0.5.0/ocm-0.5.0-darwin-arm64.tar.gz"
      sha256 "7de5005dfdaac49acd3a4b3d02ad5f3a47a08a619884629ced9fb8c86651d5cd"

      def install
        bin.install "ocm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/open-component-model/ocm/releases/download/v0.5.0/ocm-0.5.0-darwin-amd64.tar.gz"
      sha256 "f1e27667635c757cad4a5e84cf1af2685ef9546e04f9541c49444bbcb41ad811"

      def install
        bin.install "ocm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-component-model/ocm/releases/download/v0.5.0/ocm-0.5.0-linux-arm64.tar.gz"
      sha256 "6e3bd395ee044a4abf575051b58a64515eb1e8ec0339af88c365b09f915fdea2"

      def install
        bin.install "ocm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/open-component-model/ocm/releases/download/v0.5.0/ocm-0.5.0-linux-amd64.tar.gz"
      sha256 "39917d0849231a4721acd30bcc81390bc209214bf56a6c43a72c80f68ebd098c"

      def install
        bin.install "ocm"
      end
    end
  end

  test do
    system "#{bin}/ocm --version"
  end
end
