# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocm < Formula
  desc "The OCM CLI makes it easy to create component versions and embed them in build processes."
  homepage "https://ocm.software/"
  version "0.17.0"

  on_macos do
    on_intel do
      url "https://github.com/open-component-model/ocm/releases/download/v0.17.0/ocm-0.17.0-darwin-amd64.tar.gz"
      sha256 "26d5c15b14744c97ea440fdf6f2c4a1dae5214cbf108d8b45094c38e1690ae65"

      def install
        bin.install "ocm"
      end
    end
    on_arm do
      url "https://github.com/open-component-model/ocm/releases/download/v0.17.0/ocm-0.17.0-darwin-arm64.tar.gz"
      sha256 "8ecb3ef744c374269b8d397b757b423c89b811a1d9d7a86f00ce72da8162e455"

      def install
        bin.install "ocm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/open-component-model/ocm/releases/download/v0.17.0/ocm-0.17.0-linux-amd64.tar.gz"
        sha256 "4b70511c006fa1ecb39fdafdc491ef70536cdf036b9d9255dd2bc8d6fcaa24a9"

        def install
          bin.install "ocm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/open-component-model/ocm/releases/download/v0.17.0/ocm-0.17.0-linux-arm64.tar.gz"
        sha256 "570588cf7d353d397647a36be1adb65c8f97353bd6a3fda1cd1754356929aaf5"

        def install
          bin.install "ocm"
        end
      end
    end
  end

  test do
    system "#{bin}/ocm --version"
  end
end
